# Personal AI Agent Configuration
# CAP-PERSONAL-1__17571857 - Configurable Personal AI Orchestration Agent

agent_info:
  cid: "cid:centerfire:capability:17571857"
  semantic_name: "CAP-PERSONAL-1"
  display_name: "APOLLO"  # Configurable - user can change this
  version: "1.0.0"

# Core Configuration
personality:
  style: "centerfire_orchestrator"  # CI system orchestrator - direct, efficient
  verbosity: "concise"              # concise, balanced, detailed
  use_emojis: false
  response_format: "direct"
  quiet_terminal: false             # Show useful steps, skip timing details

# Model Configuration  
models:
  conversation_model: "llama2:latest"    # Primary interface model
  decision_model: "mistral:7b-instruct"  # Task routing and command generation
  
  # Specialist models (inherited from AGT-LOCAL-LLM-1)
  specialists:
    file_analyst: "codellama:13b-instruct"
    knowledge_curator: "mistral:7b-instruct"
    workflow_manager: "llama3.1:8b"

# Integration Endpoints
integrations:
  manager_endpoint: "http://localhost:8380/agents"  # AGT-MANAGER-1 for agent discovery
  commander_endpoint: "http://localhost:8090/api/agents/system"
  local_llm_endpoint: "http://localhost:8090/api/agents/localllm"
  redis_endpoint: "localhost:6380"
  weaviate_endpoint: "http://localhost:8080"

# Orchestration Settings
orchestration:
  max_parallel_tasks: 3
  task_timeout_seconds: 300
  auto_delegate: true
  conversation_memory: true
  learning_enabled: true

# Decision Rules (Fast Path)
decision_rules:
  system_analysis:
    patterns: ["count", "analyze", "measure", "calculate", "total number", "how many"]
    handler: "commander"
    
  system_commands:
    patterns: ["check if", "is running", "status of", "restart process", "stop service", "start service", "start claude", "open terminal", "tmux", "launch claude", "new session", "terminal window"]
    handler: "commander"
    
  file_operations:
    patterns: ["find files", "search for", "locate", "show me files"]
    handler: "file_analyst"
    
  workflow_management:
    patterns: ["create todo", "add task", "remind me to", "organize my", "plan my"]
    handler: "workflow_manager"
    
  context_queries:
    patterns: ["what did we discuss", "remember when", "previous conversation", "show me history", "context about", "recall our talk", "find our conversation about", "search our chat", "what was said about"]
    handler: "context_agent"

# Conversation Flow
conversation:
  greeting_message: "${display_name} ready. Centerfire Intelligence orchestrator online."
  context_window: 10  # Remember last 10 exchanges
  auto_save_conversations: true
  session_timeout_minutes: 60